name: Flutter macOS DMG Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:

    # 1️⃣ Clone Bitbucket Repository (no env)
    - name: Clone Repository
      run: |
        git clone https://first40-admin:${{ secrets.BITBUCKET_PIPELINE123 }}@bitbucket.org/trirope-tech/pinaslotto-game-client.git

    # 2️⃣ Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    # 3️⃣ Check Flutter
    - name: Check Flutter
      run: |
        which flutter
        flutter --version

    # 4️⃣ Flutter Setup
    - name: Flutter Setup
      run: |
        cd pinaslotto-game-client
        flutter clean
        flutter pub get

    # 5️⃣ Enable macOS
    - name: Enable macOS
      run: flutter config --enable-macos-desktop

    # 6️⃣ Build macOS
    - name: Build macOS
      run: |
        cd pinaslotto-game-client
        flutter build macos --release

    # 7️⃣ Install DMG tool
    - name: Install create-dmg
      run: brew install create-dmg

    # 8️⃣ Create DMG
    - name: Create DMG
      run: |
        cd pinaslotto-game-client

        APP_PATH=$(find build/macos -name "*.app" | head -n 1)

        create-dmg \
          --volname "PinaSlotto" \
          "PinaSlotto-1.0.7.dmg" \
          "$APP_PATH"

    # 9️⃣ Upload DMG (v4 fixed)
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: pinaslotto-game-client/PinaSlotto-*.dmg
