name: Flutter macOS DMG Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:

    # 1️⃣ Clone Bitbucket Repo
    - name: Clone Repository
      run: |
        git clone -b feature/common-build https://first40-admin:${{ secrets.BITBUCKET_PIPELINE123 }}@bitbucket.org/trirope-tech/pinaslotto-game-client.git
    # 2️⃣ Check root folder
    - name: Check Root Folder
      run: |
        pwd
        ls -l

    # 3️⃣ Check inside repo
    - name: Check Repo Structure
      run: |
        cd pinaslotto-game-client
        pwd
        ls -R

    # 4️⃣ Find Flutter project (IMPORTANT)
    - name: Find pubspec.yaml
      run: |
        cd pinaslotto-game-client
        find . -name pubspec.yaml

    # 5️⃣ Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    # 6️⃣ Auto detect project path
    - name: Detect Flutter Project
      run: |
        cd pinaslotto-game-client
        PROJECT_DIR=$(find . -name pubspec.yaml | head -n 1 | xargs dirname)
        echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
        echo "Detected project: $PROJECT_DIR"

    # 7️⃣ Flutter Setup
    - name: Flutter Setup
      run: |
        cd pinaslotto-game-client/${{ env.PROJECT_DIR }}
        flutter clean
        flutter pub get

    # 8️⃣ Enable macOS project
    - name: Enable macOS project
      run: |
        cd pinaslotto-game-client
        flutter config --enable-macos-desktop
        flutter create dmgbuild_1

    # 9️⃣ Build macOS
    - name: Build macOS
      run: |
        cd pinaslotto-game-client
        flutter build macos --release

    # 🔟 Install DMG tool
    - name: Install create-dmg
      run: brew install create-dmg

    # 1️⃣1️⃣ Create DMG
    - name: Create DMG
      run: |
        cd pinaslotto-game-client/${{ env.PROJECT_DIR }}

        APP_PATH=$(find build/macos -name "*.app" | head -n 1)
        echo "App path: $APP_PATH"

        create-dmg \
          --volname "PinaSlotto" \
          "PinaSlotto.dmg" \
          "$APP_PATH"

    # 1️⃣2️⃣ Upload DMG
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: pinaslotto-game-client/${{ env.PROJECT_DIR }}/PinaSlotto.dmg
